### ISSUE TITLE
AWS Load Balancer Controller

### ISSUE THREAD

**Issue by mojtabaimani** [kuberise/kuberise.io#40]
I would like to enable the [AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/) so the services ingress can have a public dns and ip address.

**Comment by mojtabaimani** [comment]
## **Tasks:**
- [x] Add a sample app-of-apps values for eks called values-eks-example.yaml 
- [x] Add values folder for eks-example in values folder.  
- [x] Add [AWS Load Balancer Controller Helm chart](https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller) to the values.yaml and values-eks-example.yaml
- [x] Add values.yaml for aws lb controller in values folder
- [ ] Configure the IAM role for the aws-lb-controller so it can create loadbalancers. 
- [ ] Add proper ingress resource to all services
- [ ] Add dns zone and external dns to config the dns, or use default aws dns

**Comment by mojtabaimani** [comment]
some references: 
https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/
https://www.youtube.com/watch?v=ZfjpWOC5eoE
